//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC5_Stock_Example.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES
    {
        public int ID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> EMPLOYE { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> REMOVE { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual EMPLOYES EMPLOYES { get; set; }
        public virtual PRODUCT PRODUCT1 { get; set; }
    }
}
